#!/bin/bash

# Set the wallpaper
~/.fehbg &

# Start authentication agent
/usr/bin/lxpolkit &

# Start clipboard manager
lxclipboard &

# Start Pamac deamon
pamac-user-daemon &

# Start Polybar
polybar bottom &

# Setup layout (US & RU), Alt+Shift to toggle between them
setxkbmap -layout us,ru -option grp:alt_shift_toggle &

# Start Redshift
redshift &

# Start screen compositor
compton -b &

# Open and close Enpass to start the "deamon"
bspc rule -a "Enpass-Desktop" -o focus="off" follow="off" &&
	bspc rule -a "Enpass-Desktop" -o focus="off" follow="off" hidden="on" &&
		enpass &

(sleep 2s && bspc node $(bspc query -N -n .hidden) -c) &

# Open Chromium & web apps on desired desktops
bspc rule -a "Chromium":"chromium" \
	-o desktop="^1" focus="on" &&
	chromium &

# bspc rule -a "Chromium":"web.skype.com" \
# 	-o desktop="^2" split_dir="east" follow="off" &&
# 	chromium --app="https://web.skype.com/" &

# bspc rule -a "Chromium":"open.spotify.com" \
# 	-o desktop="^2" split_dir="west" follow="off" &&
# 	chromium --app="https://open.spotify.com/" &
